- name: Atualizando o repo
  raw: dnf -y update

- name: Instalando o epel-release
  raw: dnf -y install epel-release

- name: Intalando o dnf-utils
  raw: dnf -y install dnf-utils

#- name: Instalando o python
#  raw: dnf -y install python39

#- name: Removendo o link simbolico python antigo
#  raw: rm /usr/bin/python"

- name: Adicionando o link simbolico do python mais recente
  raw: ln -s python3 /usr/bin/python

- name: Instalando o python-firewall
  raw: dnf -y install python-firewall

- name: Instalando o libselinux-python3
  raw: dnf -y install libselinux-python3

- name: Instalando o libsemanage-python3
  raw: dnf -y install libsemanage-python3

- name: Instalando o  python-dnf
  raw: dnf -y install python-dnf

- name: Instalando o git
  raw: dnf -y install git

- name: Instalando o tar
  raw: dnf -y install tar

- name: Instalando o wget
  raw: dnf -y install wget

- name: Instalando o bzip2
  raw: dnf -y install bzip2

- name: Instalando o unzip
  raw: dnf -y install unzip

- name: Definir hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Adicionar hostname ao /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ hostname }}"
    state: present
    create: yes

- name: Instalando os pacotes snmp
  dnf:
    name: "{{ packages }}"
    state : present
  vars:
    packages:
    - net-snmp
    - net-snmp-utils
    - perl-Crypt-Rijndael

- name: Habilitando os serviços snmpd
  systemd:
    name: snmpd
    state: started
    enabled: yes

- name: Copy snmpd /etc/firewalld/services/snmpd.xml
  copy:
    src: snmpd.xml
    dest: "/etc/firewalld/services/snmpd.xml"

- name: Permit traffic in default zone on port 22/tcp [SSH]
  firewalld:
    port: 22/tcp
    permanent: yes
    state: enabled

- name: permit traffic in default zone for http service
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: permit traffic in default zone for https service
  firewalld:
    service: https
    permanent: yes
    state: enabled

- name: permit traffic in default zone for snmp service
  firewalld:
    service: snmp
    permanent: yes
    state: enabled

- name: Reload firewalld
  shell: firewall-cmd --reload

